name: Build-Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: read

jobs:
  build-win:
    runs-on: windows-latest
    env:
      DEESEEK_API_KEY: ${{ secrets.DEESEEK_API_KEY }}
    steps:

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --name galirl app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: galirl
          path: dist/galirl.exe

      - name: Attach exe to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/galirl.exe